version: '3.9'
services:

  database:
        image: mysql:8.0.20
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        container_name: slave_ticket
        hostname: slave_ticket
        restart: always
        cap_add:
                - SYS_NICE
        environment:
                MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
                MYSQL_DATABASE: ticket
                MYSQL_USER: codeaccess
                MYSQL_PASSWORD: CODE_PASSWORD
        ports:
                - 3356:3306
        volumes:
                - /home/services/mysql/ticket/:/var/lib/mysql
                - ./etc/my.cnf:/etc/mysql/my.cnf
                - ./etc/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
                - my_service
networks:
  my_service:
    external: true
